### ISSUE TITLE
jsDeliver not working

### ISSUE THREAD

**Issue by xCette** [Inscryb/inscryb-markdown-editor#1]
https://cdn.jsdelivr.net/gh/inscryb/inscrybmde-markdown-editor@1/dist/inscrybmde.min.css

returns  _Failed to fetch version info for inscryb/inscrybmde-markdown-editor._

**Comment by MartinKolarik** [comment]
Hi, I'm Martin from jsDelivr.

For the above link to work, a GitHub release of this repo needs to be made first. However, the code is already published to npm, so you can use a npm-based link instead: https://cdn.jsdelivr.net/npm/inscrybmde@1.11.3/dist/

We actually recommend using npm links where possible, so I'd just suggest changing links in the README.

**Comment by xCette** [comment]
Fixed it, your js deliver links should be:
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/inscrybmde@1.11.3/dist/inscrybmde.min.css">
<script src="https://cdn.jsdelivr.net/npm/inscrybmde@1.11.3/dist/inscrybmde.min.js"></script>

**Comment by xCette** [comment]
and after refreshing the page I see your comment. :p

**Comment by CWharton** [comment]
Updated links on the readme.md. Thank you.

**Comment by sdcomilla1** [comment]
> Hi, I'm Martin from jsDelivr.
> 
> For the above link to work, a GitHub release of this repo needs to be made first. However, the code is already published to npm, so you can use a npm-based link instead: https://cdn.jsdelivr.net/npm/inscrybmde@1.11.3/dist/
> 
> We actually recommend using npm links where possible, so I'd just suggest changing links in the README.
Which type of change in the README have to do? 
I have understood,  gh to npm replace is fixable thats ok. But dont understand, changing about README. Please tell clearly about this. Thanks."Changing links in the README"
