### ISSUE TITLE
Clicking on preview hangs

### ISSUE THREAD

**Issue by mpierre0220** [Inscryb/inscryb-markdown-editor#10]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps

1. ...
2. ...

### Version information
Browser type and version: Chrome or FF
SimpleMDE version: unscrybmde 1.11.3

When I click on preview on a screen with some markdown data on it, the screen just says loading and hangs there. A am doing something wrong?

**Comment by CWharton** [comment]
I am not having the same issue. Can you post a link to a example so I can review the code. [Plunker](http://plnkr.co/) will allow you to do this. Also include the markdown because the might be related to the issue.

**Comment by mpierre0220** [comment]
I just cloned your repo and am running it vanilla. I am thinking that perhaps the problem might be in differences in our jQuery versions. I am running version 1.11.1. Could that be a problem?

**Comment by CWharton** [comment]
This editor has not dependency on jQuery and uses [marked](https://github.com/markedjs/marked) to render the markdown.

**Comment by CWharton** [comment]
Unable to duplicate issue and have not had a response back.
