### ISSUE TITLE
Autosave should accept callbacks

### ISSUE THREAD

**Issue by diegotoral** [Inscryb/inscryb-markdown-editor#12]
### I'm submitting a...
- [ ] Bug report
- [x] Feature request

### Description
It would be great to have a way of changing autosave's behavior. like for example to make it persist data to an API.

**Comment by CWharton** [comment]
Agree, would be glad to accept a PR. It should not be to hard to implement.

**Comment by diegotoral** [comment]
Awesome! I can work on this. 

I'm thinking of adding an extra configuration option to `autosave`, something like `action`.

Any thoughts or suggestions?

**Comment by CWharton** [comment]
Added with #13
