### ISSUE TITLE
isPreviewActive() and isSideBySideActive() not working?

### ISSUE THREAD

**Issue by docelic** [Inscryb/inscryb-markdown-editor#17]
### I'm submitting a...
- [x] Bug report

It seems that in both SimpleMDE and InscrybMDE, functions isPreviewActive() and isSideBySideActive() always return false regardless of the actual state.
Given that the implementation of these functions looks up parent HTML elements and checks for CSS classes on them, maybe it finds the wrong elements on which it checks for the appropriate class names?

### Reproduction steps
Add a button to the menu such as:

```
{ name: "preview", action: function(e) { e.togglePreview(); console.log(e.isPreviewActive());}, className: "fa fa-pencil no-disable", title: "Toggle Edit", default: false },
```

This will always say false, while for isFullscreenActive() (which does not rely on CSS class names) it works correctly.

### Version information
Latest (InscrybMDE version 1.11.4 and SimpleMDE version 1.11.2)

Thanks!

**Comment by docelic** [comment]
The issue seems to be that when the check for    /editor-preview-active/.test(preview.className)   is performed in the code, the class list does not (yet) include "editor-preview-active".

**Comment by CWharton** [comment]
I'll look into this. For now you can use. `your-editor.codemirror.getOption('fullScreen')`

**Comment by docelic** [comment]
Hey, yes, fullScreen works, but I need isPreviewActive() and isSideBySideActive() to work. From my understanding they are not "options" and cannot be read with getOption() like fullscreen can be.

**Comment by docelic** [comment]
Hey, any luck by chance? Thanks!

**Comment by CWharton** [comment]
I have not had a chance to look into it more. I will accept a PR if you find the time to work on it.

**Comment by docelic** [comment]
It is not necessarily a bug. Maybe you'll be able to judge better. We just found that the example from the initial report does not work because when we call isPreviewActive() immediately after toggling the state, the state change did not propagate yet, and isPreviewActive() returns false.
Ok, closing this since it's unclear if this is a bug or we are implementing it wrong, and I don't intend to submit a PR.
Thanks for your input, much appreciated.
