### ISSUE TITLE
Pressing "space" deleted text on Firefox mobile

### ISSUE THREAD

**Issue by SamWhited** [Inscryb/inscryb-markdown-editor#21]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps

The form doesn't work on Firefox mobile. Specifically text can be typed, but the placeholder text does not disappear so text is typed over it, and when you press space the previously typed text is removed. Otherwise buttons and formatting appear to work, and no console messages appear when Firefox is put into debug mode.

1. Type any text in the markdown form
2. Press space

### Version information

Browser type and version: Firefox 63.0a1 (nightly 2018-08-31) Android
InscrybMDE version: 1.11.4

**Comment by SamWhited** [comment]
After filing this issue I noticed that sometimes if I press backspace the text appears again, so it may be some sort of rendering or display issue. It's not actually removing the text, just hiding it.

**Comment by CWharton** [comment]
This might be a CodeMirror issue but I'll have to look into it more to verify. CodeMirror is working on version 6 that is a rewrite to modernize the editor and make it more mobile friendly. I am monitoring their progress and once it is ready I will migrate this project to the new version.

**Comment by SamWhited** [comment]
After trying a few other editors based on code mirror similar problems happen with all of them, but this project is the only one that's completely unusable. SimpleMDE still works to a certain extent, but I'm not familiar enough with the project (or how web rendering works in general) to know what might have changed since the fork. Thanks for looking into it!

**Comment by SamWhited** [comment]
Fixed by #29
