### ISSUE TITLE
Small issue when creating a quick draft

### ISSUE THREAD

**Issue by nabdullah1** [Inscryb/inscryb-markdown-editor#25]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps
When creating a Quick Draft the notification appears noting the draft has been created, however the draft itself does not appear in Page Drafts without a forced refresh of the page by the user.

### Version information
Browser type and version: Firefox Quantum 61.0.2
InscrybMDE version:

**Comment by CWharton** [comment]
Fixed.

This is an Inscryb bug, please post these bugs in [Inscryb Community](https://community.inscryb.com). Thanks for letting me know about the bug.
