### ISSUE TITLE
change default InputStyle

### ISSUE THREAD

**Issue by Grestorn** [Inscryb/inscryb-markdown-editor#28]
I have the problem that CodeMirror's default InputStyle on mobile devices ("contenteditable") creates several unintended issues. I prefer it to use "textarea" always. 

Unfortunately, this option cannot be changed after the editor has been instantiated. I can't figure out how to change CodeMirror's default setting and it also doesn't seem to be possible to forward options into CodeMirror when instantiating inscryb as far as I can see. 

How can I get around this problem?

**Comment by CWharton** [comment]
As it stands I do not believe you can do it on initiation of the InscrybMDE object. This should not be a hard feature to add though. I'll look into it more and see what I can do. I will also accept a PR if you beat me to it.

**Comment by Grestorn** [comment]
Done. Works for me :)

**Comment by CWharton** [comment]
Thanks
