### ISSUE TITLE
[Question] What were the changes since the fork?

### ISSUE THREAD

**Issue by Phosphorus-M** [Inscryb/inscryb-markdown-editor#36]
I'm new to this repository and I do not understand what change from Simple Markdown Editor ...
In EasyMDE exist a changelog in the README File but not in Inscryb MDE.

> Changes include:
> FontAwesome 5 compatibility
> Guide button works when editor is in preview mode
> Links are now https:// by default
> Small styling changes
> Support for Node 8 and beyond
> Lots of refactored code
> Links in preview will open in a new tab by default

**Comment by CWharton** [comment]
I didn't know about EasyMDE, I'll keep an eye on it. I have a changelog.md that is a bit new and has not captured all the changes. We have FontAwesome 5 compatibility as well. 

In the future and when it becomes stable, I will be adding CodeMirror 6 to the project and that will make it a lot more modern and work better with mobile.
