### ISSUE TITLE
Text-Alignment Custom Functions

### ISSUE THREAD

**Issue by catecomm** [Inscryb/inscryb-markdown-editor#4]
[X] Feature Request / Code Assistance

I know Markdown doesn't have text alignment, but I did see this editor does allow custom functions. So in theory I could add 3 buttons, left/center/right align. But I have no idea what the function code would be to add a class to the end of the line that would support text alignment.

I know in Markdown by adding `{ .text-center}` to the end of a line, it will add the class needed to center the text. The function would have to add this text when clicked/enabled, and remove it if disabled. And if possible, to have the icon selected and not selected appropriately. 

Any help in the right direction would be appreciated.

**Comment by CWharton** [comment]
On the custom toolbar add a customFunction() like this

```
{
  name: 'image',
  action: function customFunction(editor) {
    editor.codemirror.replaceSelection('INPUT HERE');
  },
  className: 'fa fa-input',
  title: 'Insert Input',
},
```

**Comment by CWharton** [comment]
This is not in the scope of the markdown standard. If you with to implement this in the editor please use a custom function in the toolbar.
