### ISSUE TITLE
IE11 - mouse slection not working

### ISSUE THREAD

**Issue by working-name** [Inscryb/inscryb-markdown-editor#40]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps
1. Open browser. 
2. Type several paragraphs. 
3. Try selecting one of the paragraphs in IE11. 
4. Kick yourself in the nutsack.
5. Load up https://simplemde.com/ in the same browser
6. Successfully select any paragraph you want.
7. Apply ice to nutsack.

### Version information
Browser type and version: IE 11.471.17134.0
InscrybMDE version: any?

**Comment by working-name** [comment]
just realized this is a fork of the now EasyMDE, and both share the same bug. Will attempt to go to source, but if you have an idea, I would appreciate any hints.

**Comment by CWharton** [comment]
I'll look into it and see what I can find.

**Comment by working-name** [comment]
Thank you. So far through trial and error I found that this is the culprit:
```js
styleSelectedText: false
```

I don't see a significant loss of function to having that set to false, and IE11 is now happy.
