### ISSUE TITLE
Update marked dependency

### ISSUE THREAD

**Issue by AlexKott** [Inscryb/inscryb-markdown-editor#45]
### I'm submitting a...
- [x] Bug report
- [ ] Feature request

### Reproduction steps

1. `npm audit` or `yarn audit` in any project using inscrybmde will show "1 moderate severity vulnerability", namely `marked`

### Version information
Browser type and version: N/A
InscrybMDE version: 1.11.6 (latest)

### Fix
The fix is pretty simple: upgrade the `marked` dependency to `^0.6.2`.

**Comment by CWharton** [comment]
Updated.
