### ISSUE TITLE
Feature request: Grammerly support

### ISSUE THREAD

**Issue by roelofjan-elsinga** [Inscryb/inscryb-markdown-editor#46]
### I'm submitting a...
- [ ] Bug report
- [x] Feature request

### Version information
Browser type and version: Chrome 76.0.3809.132
InscrybMDE version: 1.11.6

I'm not sure if this is possible in any way, so feel free to close this issue if it's not.

I'm using the editor to write blog posts and would love to be able to use Grammerly directly into the editor. In order for Grammerly to work, it needs to see a textarea with content which this editor isn't. Is there some kind of way we can trick Grammerly into picking up the text that's written and being able to suggest changes? 

If you have any pointers about possible solutions I also don't mind putting something together and creating a PR, but I'm kind of clueless about a possible solution. Your time and effort are very much appreciated!

**Comment by CWharton** [comment]
I don't think we could support any extension for textarea. The editor uses CodeMirror and composed by many divs.

**Comment by roelofjan-elsinga** [comment]
Okay, that makes sense! I'll close this.
