### ISSUE TITLE
Can you make this as Chrome or Firefox extension?

### ISSUE THREAD

**Issue by irshadc** [Inscryb/inscryb-markdown-editor#57]
### I'm submitting a...
- [ ] Bug report
- [x] Feature request

### Reproduction steps

1. Please refer https://stackoverflow.com/questions/60880197/wysiwig-markdown-editor-for-any-textarea-as-chrome-or-firefox-extension
2. Basically we want same thing to work on existing products like GitHub Pages, Youtrack documentation. If this is available as separate extension. It will be great.

### Version information
Browser type and version:
InscrybMDE version:

**Comment by CWharton** [comment]
Your request is out of scope for this project.
