### ISSUE TITLE
H2 and H3 icons not working

### ISSUE THREAD

**Issue by kieranhogg** [Inscryb/inscryb-markdown-editor#6]
### I'm submitting a...
- Bug report

### Reproduction steps

1. ... Add H2 and H3 buttons to the toolbar
2. ... Icons don't load

### Version information
Browser type and version: Chrome 66.0.3359.117
SimpleMDE version: 1.11.3

![image](https://user-images.githubusercontent.com/1820754/39397015-622fad00-4b09-11e8-9304-a4a8ddc91dbf.png)

**Comment by kieranhogg** [comment]
5.0.8

**Comment by CWharton** [comment]
I see the issue. I will release a fix for it soon

**Comment by kieranhogg** [comment]
Any chance of a new release on jsdelivr? Thanks

**Comment by kieranhogg** [comment]
Still seems to be an issue with 1.11.6:

![image](https://user-images.githubusercontent.com/1820754/47721611-f1ba5f00-dc69-11e8-8609-66138a37016b.png)

```
var simplemde = new InscrybMDE({
        element: $("#id_text")[0],
        showIcons: ["heading-2", "heading-3"]
});
```

**Comment by CWharton** [comment]
Not sure why you are having an issue. Everything seems to work for me while testing.

**Comment by kieranhogg** [comment]
Could it be because those icons are Pro?

![image](https://user-images.githubusercontent.com/1820754/47767613-d98c2380-dced-11e8-9d9a-6bce6deaffce.png)

**Comment by CWharton** [comment]
That is exactly what it is. They do not offer a free one. I will have to note this in the readme.
