### ISSUE TITLE
Support for YAML Header?

### ISSUE THREAD

**Issue by Offerel** [Inscryb/inscryb-markdown-editor#9]
### I'm submitting a...
- [x] Feature request

### Reproduction steps
Il try to use a tagging like feature with this editor. This works by using YAML in CommonMark. For example you can insert the following at the beginning of a markdown file:
```
---
tags: coding php css javascript
...
```
to add the tags coding, coding, php, css, javascript as tags. All of the separated by space character. Is there a way to support such a standard notation or at least to to not render such a part directly in the preview? I need this only in the editor visible.

**Comment by CWharton** [comment]
We can add a strip header feature to eliminate it in the preview. It should have a option to change the delimiter, and default to not active. This is not something I have time for at the moment but I will accept a PR.

**Comment by Offerel** [comment]
Il try to todo my best to find a solution and will submit something, if i found a good way. Before that, i try to implement a script for QOwnNotes (https://github.com/pbek/QOwnNotes/issues/906) and when this works as i want it, than i try the same for the editor here. But i fear this could take a while. Could you please this issue open for now? Many thx.

**Comment by Offerel** [comment]
I have created now a script for [QOwnNotes ](https://github.com/pbek/QOwnNotes) and made a P[ull Request](https://github.com/pbek/scripts). Additionally, i have found a way to support this also in [PrimitiveNotes Roundcube Plugin](https://github.com/Offerel/roundcube_primitivenotes). This plugin uses your editor since the latest release (before it was simplemde). In case of my Roundcube Plugin, i parse the markdownfile for the YAML header, remove it in the preview and extract the meta infos. If the markdown is saved, i add the YAML header again. The YAML header is fully visible and editable only in edit mode of your editor.

Since nothing must be done on your side, i close this issue for now. It's solved outside the editor. I hope this OK for you.
